### ISSUE TITLE
iPhoneX simulator - About doesn't work, gives runtime errors in red screen

### ISSUE THREAD

**Issue by neiljaywarner** [felipecarvalho/flutterstarter#5]
Gives
-
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building
_ModalScope-[LabeledGlobalKey<_ModalScopeState>#593dd](dirty, state: _ModalScopeState#21300):
type '_AnimatedEvaluation<FractionalOffset>' is not a subtype of type 'Animation<Offset>' of
'position' where
_AnimatedEvaluation is from package:flutter/src/animation/tween.dart
FractionalOffset is from package:flutter/src/painting/fractional_offset.dart
double is from dart:core
FractionalOffset is from package:flutter/src/painting/fractional_offset.dart
Animation is from package:flutter/src/animation/animation.dart
Offset is from dart:ui

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new

When the exception was thrown, this was the stack:
#0      new SlideTransition (package:flutter/src/widgets/transitions.dart:117:33)
#1      FromRightToLeft.buildTransitions (/Users/neilwarner/Library/Developer/CoreSimulator/Devices/B9C272DF-9FF2-480A-8894-7586976B4197/data/Containers/Data/Application/CD80C8A8-C8BE-4A83-A6F0-D1B1FB882BB5/tmp/heartnavdrawerdVNAnT/heartnavdrawer/lib/main.dart:48:16)
#2      _ModalScopeState.build (package:flutter/src/widgets/routes.dart:469:31)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3713:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:22)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#14     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:22)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#18     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4398:32)
#19     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726:17)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#21     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#29     ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#35     StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4618:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#43     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
#44     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
#45     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#46     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#47     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#48     BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
#49     _invoke (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:120)
#50     _drawFrame (file:///b/build/slave/Mac_Engine/build/src/flutter/lib/ui/hooks.dart:109)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: type '_AnimatedEvaluation<FractionalOffset>' is not a subtype of type 'Animation<Offset>' of 'position' where
Another exception was thrown: type '_AnimatedEvaluation<FractionalOffset>' is not a subtype of type 'Animation<Offset>' of 'position' where

**Comment by interose** [comment]
Hi, I had the same error.
This should fix it:
https://github.com/comodoro/flutterstarter/commit/7909238d69c9c41c362ca65e8b244c2bbc326e17
